### ISSUE TITLE
The GPG keys listed for the "google-chrome" repository are already installed but they are not correct for this package.

### ISSUE THREAD

**Issue by bhanupakak** [kishaningithub/setup-python-amazon-linux#10]
we have been using this action till yesterday. setup-python-amazon-linux is throwing below error now.

---> Package google-chrome-stable.x86_64 0:126.0.6478.126-1 will be updated
actions/runs/9968800181/job/27544637807#step:3:21)---> Package google-chrome-stable.x86_64 0:126.0.6478.182-1 will be an update
/9968800181/job/27544637807#step:3:22)--> Finished Dependency Resolution
actions/runs/9968800181/job/27544637807#step:3:26)================================================================================
actions/runs/9968800181/job/27544637807#step:3:27) Package                 Arch      Version               Repository        Size
[runs/9968800181/job/27544637807#step:3:28)================================================================================
/9968800181/job/27544637807#step:3:29)Updating:
actions/runs/9968800181/job/27544637807#step:3:30) google-chrome-stable    x86_64    126.0.6478.182-1      google-chrome    106 M
actions/runs/9968800181/job/27544637807#step:3:31)Transaction Summary
/actions/runs/9968800181/job/27544637807#step:3:32)================================================================================
actions/runs/9968800181/job/27544637807#step:3:33)Upgrade  1 Package
actions/runs/9968800181/job/27544637807#step:3:34)warning: /var/cache/yum/x86_64/2/google-chrome/packages/google-chrome-stable-126.0.6478.182-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 9b30acf2: NOKEY
actions/runs/9968800181/job/27544637807#step:3:35)Total size: 106 M
actions/runs/9968800181/job/27544637807#step:3:36)Downloading packages:
actions/runs/9968800181/job/27544637807#step:3:37)Retrieving key from https://dl.google.com/linux/linux_signing_key.pub
actions/runs/9968800181/job/27544637807#step:3:38)The GPG keys listed for the "google-chrome" repository are already installed but they are not correct for this package.
actions/runs/9968800181/job/27544637807#step:3:39)Check that the correct key URLs are configured for this repository.
actions/runs/9968800181/job/27544637807#step:3:40) Failing package is: google-chrome-stable-126.0.6478.182-1.x86_64
runs/9968800181/job/27544637807#step:3:41) GPG Keys are configured as: https://dl.google.com/linux/linux_signing_key.pub

**Comment by kishaningithub** [comment]
Which Amazon Linux version are you running this action in?

**Comment by bhanupakak** [comment]
Amazon Linux 2

**Comment by kishaningithub** [comment]
Are you reusing self hosted runners for multiple workflows or is a new one getting spun up everytime ?

**Comment by bhanupakak** [comment]
Google-chrome 126.0.6478.126-1 was installed in the runner, and when there was an update to the Google-chrome package, there was a conflict in gpg verification. By installing the latest version of Google Chrome, the issue was resolved.
